name: Publish documentation

on:
  push:
    branches:
      - main


jobs:
  publish_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Checkout latest tagged commit
        run: |
          git checkout $(git describe --tags --abbrev=0)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          sudo apt-get install graphviz
      - name: Build docs
        run: |
          tox -e docs
          touch build/sphinx/html/.nojekyll  # allow underscores in URL path
      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/sphinx/html
          force: false
